services:
  - type: web
    name: dnacamai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dnabackend:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
